# Generated by Django 3.2.16 on 2022-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.IntegerField()),
                ('EventName', models.TextField()),
                ('isFestival', models.IntegerField()),
                ('ImgUrl', models.TextField()),
                ('stDate', models.DateTimeField()),
                ('enDate', models.DateTimeField()),
                ('Organization', models.TextField()),
                ('Location', models.TextField()),
                ('WebsiteUrl', models.TextField()),
            ],
        ),
    ]
