# Generated by Django 3.2.16 on 2022-11-04 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInformation',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('EventID', models.TextField()),
                ('District', models.TextField()),
                ('EventName', models.TextField()),
                ('isFestival', models.IntegerField()),
                ('ImgUrl', models.TextField()),
                ('stDate', models.TextField()),
                ('edDate', models.TextField()),
                ('Organization', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('LocationID', models.TextField(unique=True)),
                ('LocationName', models.TextField()),
                ('Telno', models.TextField()),
                ('SiteUrl', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('la', models.TextField()),
                ('lo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('userdd', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oshuApp.eventinformation')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventinformation',
            name='lid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oshuApp.eventlocation'),
        ),
    ]
