# Generated by Django 3.2.16 on 2022-11-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('LocationID', models.TextField(unique=True)),
                ('LocationName', models.TextField()),
                ('Telno', models.TextField()),
                ('SiteUrl', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('la', models.TextField()),
                ('lo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventInformation',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('EventID', models.TextField()),
                ('District', models.IntegerField()),
                ('EventName', models.TextField()),
                ('isFestival', models.IntegerField()),
                ('ImgUrl', models.TextField()),
                ('stDate', models.TextField()),
                ('edDate', models.TextField()),
                ('Organization', models.TextField()),
                ('WebsiteUrl', models.TextField()),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oshuApp.eventlocation')),
            ],
        ),
    ]
