# Generated by Django 3.2.16 on 2022-11-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oshuApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userdd',
        ),
    ]
