# Generated by Django 3.2.16 on 2022-11-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshuApp', '0002_auto_20221101_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinformation',
            name='District',
            field=models.TextField(),
        ),
    ]
