# Generated by Django 3.2.16 on 2022-11-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oshuApp', '0002_remove_profile_userdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('userpw', models.TextField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventinformation',
            name='EventID',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='interestevent',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oshuApp.user'),
        ),
    ]
