# Generated by Django 3.2.16 on 2022-11-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oshuApp', '0003_alter_eventinformation_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('userpw', models.TextField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oshuApp.eventinformation')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oshuApp.user')),
            ],
        ),
    ]
