# Generated by Django 3.2.16 on 2022-11-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oshuApp', '0003_auto_20221108_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userpw',
            new_name='userPW',
        ),
    ]
