# Generated by Django 3.2.16 on 2022-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshuApp', '0004_auto_20221108_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestevent',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='interestevent',
            name='userid',
        ),
        migrations.AddField(
            model_name='interestevent',
            name='eventID',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='interestevent',
            name='userID',
            field=models.TextField(default='default'),
        ),
    ]
